---
name: pre-commit
on:
  pull_request:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    environment: cachix
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v12
        with:
          name: eomii
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run pre-commit hooks
        run: |
          nix flake check -L
